- id: '1517611124119'
  alias: Away
  trigger:
  - platform: state
    entity_id: group.all_devices
    to: not_home
  action:
  - service: switch.turn_off
    data:
      entity_id: group.all_switches
  - service: media_player.turn_off
    data:
      entity_id: media_player.denon_avrx2200w
