homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  base_url: !secret http_base_url
  server_port: !secret http_server_port
  api_password: !secret http_password
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor: !include_dir_list sensors/

# Text to speech
tts:
  - platform: google

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

# Z-Wave
zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_network_key
  polling_interval: 10000
  device_config:
    switch.aeotec_zw116_nano_switch_master_bedroom_switch:
      refresh_value: true
      delay: 7
      polling_intensity: 1
    switch.leviton_dz15s1bz_switch_guest_bedroom_switch:
      refresh_value: true
      delay: 4
      polling_intensity: 1
    switch.leviton_dzr151rz_outlet_living_room_switch:
      refresh_value: true
      delay: 4
      polling_intensity: 1

# Emulated Hue
emulated_hue:
  host_ip: !secret pi_ip
  listen_port: !secret hue_bridge_port
  expose_by_default: true
  exposed_domains: switch

# Media Devices
media_player:
  - platform: dunehd
    host: dune.home
  - platform: firetv
    device: firetv
#  - platform: denonavr
#    host: denon.home
#    name: denon

ios:

# MQTT
mqtt:
  broker: core-mosquitto
  username: !secret mqtt_username
  password: !secret mqtt_password

# Device Tracking
device_tracker:
  - platform: owntracks
    max_gps_accuracy: 500
  - platform: ddwrt
    host: !secret router_ip
    username: !secret router_username
    password: !secret router_password
    consider_home: 420
    interval_seconds: 15

logger:
  default: info
  logs:
    homeassistant.components.mqtt: debug

panel_iframe:
  terminal:
    title: Terminal
    icon: mdi:console
    url: !secret terminal_url
  ide:
    title: IDE
    icon: mdi:code-braces
    url: !secret ide_url

zone: !include_dir_list zones/

notify:
  platform: html5
  gcm_api_key: !secret gcm_api_key
  gcm_sender_id: !secret gcm_sender_id
